
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.SocketTimeoutException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author soverine
 */
public class Server extends javax.swing.JFrame {
    static String user = "Test";
    static PrintWriter out;
    static ServerSocket server;
    static Socket sock;
    static Scanner input;
    static ArrayList<Socket> socks = new ArrayList<Socket>();
    
    static Color nickColor = new Color(193, 124, 13);
    static int pt = 16;
    static ImageIcon icon;
    static String lastMsg = "";
    
    JPanel jPanel;
    //ArrayList<PrintWriter> outputs = new ArrayList<PrintWriter>();
    
    class listener extends Thread{
        Scanner input = null;
        Socket sock;
        
        public listener(Socket sock){
            this.sock = sock;
        }
        
        public void run(){
            try{
                input = new Scanner(sock.getInputStream());
            }catch(IOException ex){
                System.out.println("Inputstream hatası.");
            }
            
            while(true){
                    if(input.hasNextLine()){
                        //DefaultTableModel model = (DefaultTableModel) jChat.getModel();
                        String s = input.nextLine();
                        String[] array = s.split("\\|");
                        //model.addRow(array);
                        System.out.println(s);
                    }
                }
            }
        }
    
    class clientListener extends Thread{
            public void run(){
                while(true){
                    try {
                        Socket client = server.accept();
                        socks.add(client);
                        System.out.println("İstemci bağlandı!");
                        listener list = new listener(client);
                        list.start();
                    } catch (SocketTimeoutException e) {
                        System.out.println("Bağlantı yok.");
                    } catch (IOException ex) {
                        Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
    }
    
    /**
     * Creates new form Server
     */
    public Server(String u) {
        try {
            user = u;
            JFileChooser fc = new JFileChooser();
            int r = fc.showDialog(this, "Onayla");
            
            if(r == JFileChooser.APPROVE_OPTION){
                icon = new ImageIcon(fc.getSelectedFile().getAbsolutePath());
                icon = new ImageIcon(icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
            }
            server = new ServerSocket(9806);
            server.setSoTimeout(3000);
            //sock = server.accept();
            //input = new Scanner(sock.getInputStream());
            //out = new PrintWriter(sock.getOutputStream(), true);
            clientListener clist = new clientListener();
            
            clist.start();
        } catch (IOException ex) {
            Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        jPanel = new JPanel();
        jPanel.setLayout(new BoxLayout(jPanel, BoxLayout.Y_AXIS)); // ✅ Buraya BoxLayout verilir
        jPane.setViewportView(jPanel); // ✅ ScrollPane'e panel atanır
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jMesaj = new javax.swing.JTextField();
        jPane = new javax.swing.JScrollPane();
        jAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IP: ");

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("192.168.2.1");
        jTextField1.setFocusable(false);

        jToggleButton1.setBackground(new java.awt.Color(51, 51, 51));
        jToggleButton1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Gönder");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jMesaj.setBackground(new java.awt.Color(51, 51, 51));
        jMesaj.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jMesaj.setForeground(new java.awt.Color(255, 255, 255));

        jPane.setBackground(new java.awt.Color(51, 51, 51));
        jPane.setForeground(new java.awt.Color(51, 51, 51));

        jAdd.setBackground(new java.awt.Color(51, 51, 51));
        jAdd.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jAdd.setForeground(new java.awt.Color(255, 255, 255));
        jAdd.setText("Ekle");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1202, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(964, 964, 964))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jMesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addComponent(jPane))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPane, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jMesaj)
                        .addComponent(jAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        JPanel mPane = new JPanel();
        mPane.setLayout(new BoxLayout(mPane, BoxLayout.X_AXIS));
        mPane.setAlignmentX(Component.LEFT_ALIGNMENT);
        
        JPanel tPane = new JPanel();
        tPane.setLayout(new BoxLayout(tPane, BoxLayout.Y_AXIS));
        
        JLabel label2 = new JLabel(jMesaj.getText());
        
        if(!lastMsg.equals(user)){
            JLabel label1 = new JLabel(user);
            JLabel label3 = new JLabel(icon);
            
            label1.setFont(new Font("Arial", Font.BOLD, pt));
            label1.setForeground(nickColor);
        
            label3.setBorder(BorderFactory.createEmptyBorder(5,5,5,5));
            label1.setBorder(BorderFactory.createEmptyBorder(0,0,0,8));
            
            tPane.add(label1);
            mPane.add(label3);
            label2.setBorder(BorderFactory.createEmptyBorder(0,0,18,0));
        }else{
            label2.setBorder(BorderFactory.createEmptyBorder(0,60,0,0));
            mPane.setAlignmentY(Component.TOP_ALIGNMENT);
            tPane.setAlignmentY(Component.TOP_ALIGNMENT);
        }
        
        
        
        label2.setFont(new Font("Arial", Font.PLAIN, pt));
        
        
        
        tPane.add(label2);
        
        mPane.add(tPane);
        
        jPanel.add(mPane);
        
        //mPane.revalidate();
        //mPane.repaint();
        jPanel.revalidate();
        jPanel.repaint();
        
        JScrollBar vertical = jPane.getVerticalScrollBar();
        
        lastMsg = user;
        SwingUtilities.invokeLater(() -> vertical.setValue(vertical.getMaximum()));
        for(Socket sock : socks){
            try {
                //DefaultTableModel model = (DefaultTableModel) jChat.getModel();
                out = new PrintWriter(sock.getOutputStream(), true);
                out.println(user + "|" + jMesaj.getText());
                String[] array = {user, jMesaj.getText()};
                //model.addRow(array);
                
            } catch (IOException ex) {
                Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server(user).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jMesaj;
    private javax.swing.JScrollPane jPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

}
